#Protein Global Alignment Code 
#Averi Pike (alp4337), FB (), Nadja La Point ()



global_alignment <- function(seq1, seq2, match_score, mismatch_score, gap_penalty) {
  
  nrow <- nchar(seq1) + 1
  ncol <- nchar(seq2) + 1
  matrix <- matrix(0, nrow = nrow, ncol = ncol)
  
  matrix[1, ] <- 0:(ncol - 1) * gap_penalty
  matrix[, 1] <- 0:(nrow - 1) * gap_penalty
  
  for (i in 2:nrow) {
    for (j in 2:ncol) {
      if (substring(seq1, i - 1, i - 1) == substring(seq2, j - 1, j - 1)) {
        diagonal_score <- matrix[i - 1, j - 1] + match_score
      } else {
        diagonal_score <- matrix[i - 1, j - 1] + mismatch_score
      }
      
      left_score <- matrix[i, j - 1] + gap_penalty
      up_score <- matrix[i - 1, j] + gap_penalty
      
      matrix[i, j] <- max(diagonal_score, left_score, up_score)
    }
  }
  
  print("Alignment Matrix (Subset):")
  print(matrix[1:10, 1:10])  
  
  i <- nrow
  j <- ncol
  align_seq1 <- ""
  align_seq2 <- ""
  while (i > 1 || j > 1) {
    if (i > 1 && j > 1 && matrix[i, j] == matrix[i - 1, j - 1] + (match_score * (substring(seq1, i - 1, i - 1) == substring(seq2, j - 1, j - 1)) + mismatch_score * (substring(seq1, i - 1, i - 1) != substring(seq2, j - 1, j - 1)))) {
      align_seq1 <- paste(substring(seq1, i - 1, i - 1), align_seq1, sep = "")
      align_seq2 <- paste(substring(seq2, j - 1, j - 1), align_seq2, sep = "")
      i <- i - 1
      j <- j - 1
    } else if (i > 1 && matrix[i, j] == matrix[i - 1, j] + gap_penalty) {
      align_seq1 <- paste(substring(seq1, i - 1, i - 1), align_seq1, sep = "")
      align_seq2 <- paste("-", align_seq2, sep = "")
      i <- i - 1
    } else {
      align_seq1 <- paste("-", align_seq1, sep = "")
      align_seq2 <- paste(substring(seq2, j - 1, j - 1), align_seq2, sep = "")
      j <- j - 1
    }
  }
  
  alignment_score <- matrix[nrow, ncol]
  
  print("Aligned Sequences:")
  print("Sequence 1", align_seq1)
  print("Sequence 2", align_seq2)
  print(paste("Score:", alignment_score))
}


global_alignment("MSFRAARLSMRNRRNDTLDSTRTLYSSASRSTDLSYSESDLVNFIQANFKKRECVFFTKDSKATENVCKC
GYAQSQHMEGTQINQSEKWNYKKHTKEFPTDAFGDIQFETLGKKGKYIRLSCDTDAEILYELLTQHWHLK
TPNLVISVTGGAKNFALKPRMRKIFSRLIYIAQSKGAWILTGGTHYGLMKYIGEVVRDNTISRSSEENIV
AIGIAAWGMVSNRDTLIRNCDAEGYFLAQYLMDDFTRDPLYILDNNHTHLLLVDNGCHGHPTVEAKLRNQ
LEKYISERTIQDSNYGGKIPIVCFAQGGGKETLKAINTSIKNKIPCVVVEGSGQIADVIASLVEVEDALT
SSAVKEKLVRFLPRTVSRLPEEETESWIKWLKEILECSHLLTVIKMEEAGDEIVSNAISYALYKAFSTSE
QDKDNWNGQLKLLLEWNQLDLANDEIFTNDRRWESADLQEVMFTALIKDRPKFVRLFLENGLNLRKFLTH
DVLTELFSNHFSTLVYRNLQIAKNSYNDALLTFVWKLVANFRRGFRKEDRNGRDEMDIELHDVSPITRHP
LQALFIWAILQNKKELSKVIWEQTRGCTLAALGASKLLKTLAKVKNDINAAGESEELANEYETRAVELFT
ECYSSDEDLAEQLLVYSCEAWGGSNCLELAVEATDQHFIAQPGVQNFLSKQWYGEISRDTKNWKIILCLF
IIPLVGCGFVSFRKKPVDKHKKLLWYYVAFFTSPFVVFSWNVVFYIAFLLLFAYVLLMDFHSVPHPPELV
LYSLVFVLFCDEVRQWYVNGVNYFTDLWNVMDTLGLFYFIAGIVFRLHSSNKSSLYSGRVIFCLDYIIFT
LRLIHIFTVSRNLGPKIIMLQRMLIDVFFFLFLFAVWMVAFGVARQGILRQNEQRWRWIFRSVIYEPYLA
MFGQVPSDVDGTTYDFAHCTFTGNESKPLCVELDEHNLPRFPEWITIPLVCIYMLSTNILLVNLLVAMFG
YTVGTVQENNDQVWKFQRYFLVQEYCSRLNIPFPFIVFAYFYMVVKKCFKCCCKEKNMESSVCCFKNEDN
ETLAWEGVMKENYLVKINTKANDTSEEMRHRFRQLDTKLNDLKGLLKEIANKIK", "MQSVVSTGTMRHRRNGNFESSRLLNSSISRSIDVSCNDSDLVNFIRENFKKRECVFFTKDSNSVGNLCKC
GYPESQHIEGTQINDDEKWNYRKHTKELPTDAFGDVHFENIEKRGKYIRLSCDTDPETLYDLMTQHWHLK
TPNLVISVTGGAKNFALKPRMRKIFSRLIYIAQSKGAWIFTGGTHNGLMKYIGEVVRDNTISQSSEESVV
AIGIAAWGMISNRESLIRSSDNEGYYLAHYIMDDLKRDPLYCLDNNHTHLLLVDNGTHGHPTIEAEVRTQ
LEKYISERVIPESNYGGKIPIVCFAQGGGKETLKSIHVAIKSKIPCVVVEGSGRIADVIASLMEAEDTLT
SSCVKESLHRYLPRTISRLSEEETESWVKWIKEVLENPHLLTVIKTEEAGDEIVSNAIAFALYKAFSTNE
RNRDNWNEQLKLLLEWNQLDLASDEIFTNDRNWESADLQDVMFTALVKDRPKFVRLFLENGLNLRKFLTT
EVLRELYTNNFSSLVFKNLQIAKNSYNDALLTFVWKMVEDFRRGLKRDDKNNKHELEIHLSTECPITRHP
LQALFIWSVLQNKKELSKVIWEQTRGCTLAALGASKLLKSMAKVKNDINAAGESEELANEYETRAVELFT
ECYSNDENLAEQLLTYSCEAWGGSNCLELAVEAKDQQFIAQPGVQNFLSKQWYGGISRDTNNWKIILCLF
FFPLIGCGFISFRKKPVEKSKKLFLYYVSFFTSPFVVFSWNVIFYIVFLLLFAYVLLMDFQKEPTVLEII
LYVLVFILLCDEVRQWYMNGSKYLSDLWNVMDTLAIFYFIAGIVLRLHSSNESSWYSGRVIFCLDYIVFT
LRLIHIFTVSRNLGPKIIMLQRMMIDVFFFLFLFAVWMVAFGVARQGILRKNEHRWEWIFRSVIYEPYLA
MFGQYPDDVDGTTYNFDRCTFSGNESKPLCVELDANNQPRFPEWITIPLVCIYMLSTNILLVNLLVAMFG
YTVGSVQENNDQVWKFQRYFLVQEYCSRLTIPFPFVIFAYIFMVMRKCFKCCCKNESKEPSICCSRNEDN
ETLSWEAVMKENYLVKINTKASDTSEEMVHRFRQLDAKLSDLKGLLKEISSKIK
", match_score=3, mismatch_score=-10, gap_penalty=-3)

  
 